name: Ktor Server CI/CD
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Give Gradle Wrapper permission
        run: chmod +x ./gradlew

      - name: Build the project
        run: ./gradlew build

      - name: Run tests
        run: ./gradlew test